In [1]:
import pandas as pd

In [2]:
team = 'chi'
year_range = range(2002,2020)
bear_dict = {}

In [3]:
# produces dictionary of dataframes for years in year_range, then adds a column specifying year
for year in year_range:
    print(year)
    url = f'https://www.pro-football-reference.com/teams/{team}/{year}.htm'
    bear_data = pd.read_html(url, header=1)
    bear_dict[year] = bear_data[1]
    bear_dict[year]['year'] = year

2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019

In [4]:
bear_dict[2002].head(3)

,Week,Day,Date,Unnamed: 3,Unnamed: 4,Unnamed: 5,OT,Rec,Unnamed: 8,Opp,...,TO,1stD.1,TotYd.1,PassY.1,RushY.1,TO.1,Offense,Defense,Sp. Tms,year
0,1,Sun,September 8,1:04PM ET,boxscore,W,NaN,1-0,NaN,Minnesota Vikings,...,2.0,19.0,368.0,228.0,140.0,3.0,6.37,-1.20,1.01,2002
1,2,Sun,September 15,1:04PM ET,boxscore,W,NaN,2-0,@,Atlanta Falcons,...,2.0,19.0,257.0,135.0,122.0,3.0,-9.67,8.39,3.54,2002
2,3,Sun,September 22,1:05PM ET,boxscore,L,NaN,2-1,NaN,New Orleans Saints,...,2.0,18.0,302.0,229.0,73.0,3.0,0.58,-0.64,-6.03,2002

In [5]:
# appends all separate dataframes into a single frame
full_bear = pd.DataFrame()
for i in bear_dict:
    full_bear = full_bear.append(bear_dict[i], ignore_index=True)

In [6]:
full_bear.head(10)

,Week,Day,Date,Unnamed: 3,Unnamed: 4,Unnamed: 5,OT,Rec,Unnamed: 8,Opp,...,TO,1stD.1,TotYd.1,PassY.1,RushY.1,TO.1,Offense,Defense,Sp. Tms,year
0,1,Sun,September 8,1:04PM ET,boxscore,W,NaN,1-0,NaN,Minnesota Vikings,...,2.0,19.0,368.0,228.0,140.0,3.0,6.37,-1.20,1.01,2002
1,2,Sun,September 15,1:04PM ET,boxscore,W,NaN,2-0,@,Atlanta Falcons,...,2.0,19.0,257.0,135.0,122.0,3.0,-9.67,8.39,3.54,2002
2,3,Sun,September 22,1:05PM ET,boxscore,L,NaN,2-1,NaN,New Orleans Saints,...,2.0,18.0,302.0,229.0,73.0,3.0,0.58,-0.64,-6.03,2002
3,4,Sun,September 29,1:04PM ET,boxscore,L,OT,2-2,@,Buffalo Bills,...,NaN,26.0,410.0,307.0,103.0,1.0,3.14,-7.40,0.06,2002
4,5,Mon,October 7,9:08PM ET,boxscore,L,NaN,2-3,NaN,Green Bay Packers,...,4.0,20.0,457.0,333.0,124.0,1.0,-12.87,-3.38,8.55,2002
5,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bye Week,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2002
6,7,Sun,October 20,1:03PM ET,boxscore,L,OT,2-4,@,Detroit Lions,...,3.0,23.0,362.0,170.0,192.0,1.0,-16.57,-1.40,13.03,2002
7,8,Sun,October 27,1:00PM ET,boxscore,L,NaN,2-5,@,Minnesota Vikings,...,3.0,24.0,364.0,216.0,148.0,1.0,-16.75,-6.35,1.32,2002
8,9,Sun,November 3,1:05PM ET,boxscore,L,NaN,2-6,NaN,Philadelphia Eagles,...,1.0,23.0,309.0,192.0,117.0,1.0,-8.98,1.96,0.70,2002
9,10,Sun,November 10,4:15PM ET,boxscore,L,NaN,2-7,NaN,New England Patriots,...,1.0,19.0,397.0,315.0,82.0,2.0,-6.40,2.32,2.19,2002

In [7]:
for i in full_bear.columns:
    print(i)

Week
Day
Date
Unnamed: 3
Unnamed: 4
Unnamed: 5
OT
Rec
Unnamed: 8
Opp
Tm
Opp.1
1stD
TotYd
PassY
RushY
TO
1stD.1
TotYd.1
PassY.1
RushY.1
TO.1
Offense
Defense
Sp. Tms
year

In [8]:
# Dataframe Cleanup
column_clean_dict =  {'Unnamed: 3':'Kickoff_time',
     'Unnamed: 5': 'W/L',
     'Unnamed: 8' : 'Home/Away',
     'Tm' : 'Team_Score',
     'Opp.1' : 'Oppo_score',
     '1stD' : '1D_gained',
     'TotYd' : 'Team_Total_Yards',
     'PassY' : 'Team_Pass_Yards',
     'RushY' : 'Team_Rush_Yards',
     'TO' : 'team_turnover',
     '1stD.1' : '1D_allowed',
     'TotYd.1' : 'oppo_total_yards',
     'PassY.1' : 'oppo_pass_yards',
     'RushY.1' : 'oppo_rush_yards',
     'TO.1' : 'oppo_turnover',
     'Offense' : 'offense_expected_points',
     'Defense' : 'defense_expected_points',
     'Sp. Tms' : 'sp_expected_points'
    }

In [9]:
full_bear.rename(column_clean_dict, inplace=True, axis=1)

full_bear.drop('Unnamed: 4', axis=1, inplace=True)

full_bear.drop(full_bear[full_bear['Week'] == 'Playoffs'].index, inplace=True, axis=0)

In [10]:


full_bear['OT'].fillna(value=0, inplace=True)
full_bear['OT'].replace({'OT': 1}, inplace=True)

full_bear['Home/Away'].fillna(value='HOME', inplace=True)
full_bear['Home/Away'].replace({'@': 'AWAY'}, inplace=True)

full_bear['team_turnover'].fillna(value=0, inplace=True)
full_bear['oppo_turnover'].fillna(value=0, inplace=True)
full_bear.tail(10)

,Week,Day,Date,Kickoff_time,W/L,OT,Rec,Home/Away,Opp,Team_Score,...,team_turnover,1D_allowed,oppo_total_yards,oppo_pass_yards,oppo_rush_yards,oppo_turnover,offense_expected_points,defense_expected_points,sp_expected_points,year
307,8,Sun,October 27,1:00PM ET,L,0,3-4,HOME,Los Angeles Chargers,16.0,...,2.0,11.0,231.0,195.0,36.0,1.0,0.44,5.45,-6.02,2019
308,9,Sun,November 3,1:00PM ET,L,0,3-5,AWAY,Philadelphia Eagles,14.0,...,1.0,26.0,373.0,227.0,146.0,0.0,-4.78,-10.73,2.82,2019
309,10,Sun,November 10,1:00PM ET,W,0,4-5,HOME,Detroit Lions,20.0,...,0.0,21.0,357.0,259.0,98.0,1.0,-0.41,6.77,-2.10,2019
310,11,Sun,November 17,8:20PM ET,L,0,4-6,AWAY,Los Angeles Rams,7.0,...,1.0,13.0,283.0,173.0,110.0,2.0,-13.17,5.69,-5.08,2019
311,12,Sun,November 24,1:00PM ET,W,0,5-6,HOME,New York Giants,19.0,...,2.0,14.0,243.0,134.0,109.0,1.0,-7.02,12.48,-2.01,2019
312,13,Thu,November 28,12:30PM ET,W,0,6-6,AWAY,Detroit Lions,24.0,...,1.0,19.0,364.0,259.0,105.0,1.0,8.33,-6.28,0.13,2019
313,14,Thu,December 5,8:20PM ET,W,0,7-6,HOME,Dallas Cowboys,31.0,...,2.0,22.0,408.0,326.0,82.0,0.0,10.48,-10.67,8.71,2019
314,15,Sun,December 15,1:00PM ET,L,0,7-7,AWAY,Green Bay Packers,13.0,...,3.0,12.0,292.0,192.0,100.0,0.0,-4.89,2.97,-1.24,2019
315,16,Sun,December 22,8:20PM ET,L,0,7-8,HOME,Kansas City Chiefs,3.0,...,0.0,25.0,350.0,244.0,106.0,0.0,-6.38,-14.74,-1.09,2019
316,17,Sun,December 29,1:00PM ET,W,0,8-8,AWAY,Minnesota Vikings,21.0,...,1.0,14.0,300.0,126.0,174.0,3.0,1.26,-2.15,-1.08,2019

In [11]:
full_bear.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 317 entries, 0 to 316
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Week                     313 non-null    object
 1   Day                      295 non-null    object
 2   Date                     299 non-null    object
 3   Kickoff_time             295 non-null    object
 4   W/L                      295 non-null    object
 5   OT                       317 non-null    int64
 6   Rec                      295 non-null    object
 7   Home/Away                317 non-null    object
 8   Opp                      313 non-null    object
 9   Team_Score               295 non-null    float64
 10  Oppo_score               295 non-null    float64
 11  1D_gained                295 non-null    float64
 12  Team_Total_Yards         295 non-null    float64
 13  Team_Pass_Yards          295 non-null    float64
 14  Team_Rush_Yards          295 non-null    float64
 15  team_turnover            317 non-null    float64
 16  1D_allowed               295 non-null    float64
 17  oppo_total_yards         295 non-null    float64
 18  oppo_pass_yards          295 non-null    float64
 19  oppo_rush_yards          295 non-null    float64
 20  oppo_turnover            317 non-null    float64
 21  offense_expected_points  295 non-null    float64
 22  defense_expected_points  295 non-null    float64
 23  sp_expected_points       295 non-null    float64
 24  year                     317 non-null    int64
dtypes: float64(15), int64(2), object(8)
memory usage: 64.4+ KB

In [12]:
full_bear.to_excel('bear_data_test.xlsx', sheet_name='Bears')

In [13]:
bye_week = full_bear[full_bear['Opp']=='Bye Week'].index
full_bear.drop(bye_week, inplace=True)

In [14]:
drop_index = full_bear[full_bear['Date']=='Playoffs'].index
full_bear.drop(drop_index, inplace=True)

In [15]:
full_bear.head()

,Week,Day,Date,Kickoff_time,W/L,OT,Rec,Home/Away,Opp,Team_Score,...,team_turnover,1D_allowed,oppo_total_yards,oppo_pass_yards,oppo_rush_yards,oppo_turnover,offense_expected_points,defense_expected_points,sp_expected_points,year
0,1,Sun,September 8,1:04PM ET,W,0,1-0,HOME,Minnesota Vikings,27.0,...,2.0,19.0,368.0,228.0,140.0,3.0,6.37,-1.20,1.01,2002
1,2,Sun,September 15,1:04PM ET,W,0,2-0,AWAY,Atlanta Falcons,14.0,...,2.0,19.0,257.0,135.0,122.0,3.0,-9.67,8.39,3.54,2002
2,3,Sun,September 22,1:05PM ET,L,0,2-1,HOME,New Orleans Saints,23.0,...,2.0,18.0,302.0,229.0,73.0,3.0,0.58,-0.64,-6.03,2002
3,4,Sun,September 29,1:04PM ET,L,1,2-2,AWAY,Buffalo Bills,27.0,...,0.0,26.0,410.0,307.0,103.0,1.0,3.14,-7.40,0.06,2002
4,5,Mon,October 7,9:08PM ET,L,0,2-3,HOME,Green Bay Packers,21.0,...,4.0,20.0,457.0,333.0,124.0,1.0,-12.87,-3.38,8.55,2002

In [16]:
# splitting out the date column for transformation into datetime object
month_list = []
for i in full_bear['Date']:
    month_list.append(i)
    
month_split = []
for i in month_list:
    month_split.append(i.split()[0])

day_split = []
for i in month_list:
    day_split.append(i.split()[1])

full_bear['Month'] = month_split
full_bear['Day'] = day_split

In [17]:
month_dict = {
    'September' : 9,
    'Octover' : 10,
    'November' : 11,
    'December' : 12,
    'January' : 1,
    'February': 2
}

In [18]:
full_bear['Month'].replace(month_dict, inplace=True)

In [19]:
full_bear['W/L'].value_counts()

L    153
W    142
Name: W/L, dtype: int64

In [20]:
full_bear.head()

,Week,Day,Date,Kickoff_time,W/L,OT,Rec,Home/Away,Opp,Team_Score,...,1D_allowed,oppo_total_yards,oppo_pass_yards,oppo_rush_yards,oppo_turnover,offense_expected_points,defense_expected_points,sp_expected_points,year,Month
0,1,8,September 8,1:04PM ET,W,0,1-0,HOME,Minnesota Vikings,27.0,...,19.0,368.0,228.0,140.0,3.0,6.37,-1.20,1.01,2002,9
1,2,15,September 15,1:04PM ET,W,0,2-0,AWAY,Atlanta Falcons,14.0,...,19.0,257.0,135.0,122.0,3.0,-9.67,8.39,3.54,2002,9
2,3,22,September 22,1:05PM ET,L,0,2-1,HOME,New Orleans Saints,23.0,...,18.0,302.0,229.0,73.0,3.0,0.58,-0.64,-6.03,2002,9
3,4,29,September 29,1:04PM ET,L,1,2-2,AWAY,Buffalo Bills,27.0,...,26.0,410.0,307.0,103.0,1.0,3.14,-7.40,0.06,2002,9
4,5,7,October 7,9:08PM ET,L,0,2-3,HOME,Green Bay Packers,21.0,...,20.0,457.0,333.0,124.0,1.0,-12.87,-3.38,8.55,2002,October