In [1]:
import requests
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('ggplot')

In [2]:
team = 'chi'
year_range = range(2000,2020)
bear_dict = {}

In [3]:
# produces dictionary of dataframes for years in year_range, then adds a column specifying year
for year in year_range:
    print(year)
    url = f'https://www.pro-football-reference.com/teams/{team}/{year}.htm'
    bear_data = pd.read_html(url, header=1)
    bear_dict[year] = bear_data[1]
    bear_dict[year]['year'] = year

2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019

In [4]:
bear_dict[2000].head(3)

,Week,Day,Date,Unnamed: 3,Unnamed: 4,Unnamed: 5,OT,Rec,Unnamed: 8,Opp,...,TO,1stD.1,TotYd.1,PassY.1,RushY.1,TO.1,Offense,Defense,Sp. Tms,year
0,1,Sun,September 3,1:00PM ET,boxscore,L,NaN,0-1,@,Minnesota Vikings,...,1.0,17.0,374.0,188.0,186.0,1.0,13.33,-11.18,-4.30,2000
1,2,Sun,September 10,1:01PM ET,boxscore,L,NaN,0-2,@,Tampa Bay Buccaneers,...,4.0,21.0,327.0,171.0,156.0,NaN,-35.01,-8.90,1.97,2000
2,3,Sun,September 17,3:16PM ET,boxscore,L,NaN,0-3,NaN,New York Giants,...,1.0,23.0,409.0,237.0,172.0,1.0,-12.65,-7.19,8.02,2000

In [5]:
# appends all separate dataframes into a single frame
full_bear = pd.DataFrame()
for i in bear_dict:
    full_bear = full_bear.append(bear_dict[i], ignore_index=False)

In [6]:
full_bear.head(10)

,Week,Day,Date,Unnamed: 3,Unnamed: 4,Unnamed: 5,OT,Rec,Unnamed: 8,Opp,...,TO,1stD.1,TotYd.1,PassY.1,RushY.1,TO.1,Offense,Defense,Sp. Tms,year
0,1,Sun,September 3,1:00PM ET,boxscore,L,NaN,0-1,@,Minnesota Vikings,...,1.0,17.0,374.0,188.0,186.0,1.0,13.33,-11.18,-4.30,2000
1,2,Sun,September 10,1:01PM ET,boxscore,L,NaN,0-2,@,Tampa Bay Buccaneers,...,4.0,21.0,327.0,171.0,156.0,NaN,-35.01,-8.90,1.97,2000
2,3,Sun,September 17,3:16PM ET,boxscore,L,NaN,0-3,NaN,New York Giants,...,1.0,23.0,409.0,237.0,172.0,1.0,-12.65,-7.19,8.02,2000
3,4,Sun,September 24,1:02PM ET,boxscore,L,NaN,0-4,NaN,Detroit Lions,...,5.0,15.0,274.0,194.0,80.0,1.0,-15.69,8.30,-0.80,2000
4,5,Sun,October 1,4:15PM ET,boxscore,W,NaN,1-4,@,Green Bay Packers,...,NaN,22.0,364.0,320.0,44.0,3.0,1.20,6.05,-4.07,2000
5,6,Sun,October 8,1:03PM ET,boxscore,L,NaN,1-5,NaN,New Orleans Saints,...,3.0,24.0,403.0,217.0,186.0,1.0,-15.93,-7.04,2.11,2000
6,7,Sun,October 15,8:35PM ET,boxscore,L,NaN,1-6,NaN,Minnesota Vikings,...,NaN,17.0,368.0,177.0,191.0,1.0,-1.58,-10.76,-1.71,2000
7,8,Sun,October 22,1:03PM ET,boxscore,L,NaN,1-7,@,Philadelphia Eagles,...,1.0,17.0,298.0,201.0,97.0,2.0,-11.20,8.86,-1.15,2000
8,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bye Week,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000
9,10,Sun,November 5,1:02PM ET,boxscore,W,NaN,2-7,NaN,Indianapolis Colts,...,NaN,20.0,371.0,281.0,90.0,2.0,7.91,-0.90,-1.93,2000

In [7]:
for i in full_bear.columns:
    print(i)

Week
Day
Date
Unnamed: 3
Unnamed: 4
Unnamed: 5
OT
Rec
Unnamed: 8
Opp
Tm
Opp.1
1stD
TotYd
PassY
RushY
TO
1stD.1
TotYd.1
PassY.1
RushY.1
TO.1
Offense
Defense
Sp. Tms
year

In [8]:
# Dataframe Cleanup
column_clean_dict =  {'Unnamed: 3':'Kickoff_time',
     'Unnamed: 5': 'W/L',
     'Unnamed: 8' : 'Home/Away',
     'Tm' : 'Team_Score',
     'Opp.1' : 'Oppo_score',
     '1stD' : '1D_gained',
     'TotYd' : 'Team_Total_Yards',
     'PassY' : 'Team_Pass_Yards',
     'RushY' : 'Team_Rush_Yards',
     'TO' : 'team_turnover',
     '1stD.1' : '1D_allowed',
     'TotYd.1' : 'oppo_total_yards',
     'PassY.1' : 'oppo_pass_yards',
     'RushY.1' : 'oppo_rush_yards',
     'TO.1' : 'oppo_turnover',
     'Offense' : 'offense_expected_points',
     'Defense' : 'defense_expected_points',
     'Sp. Tms' : 'sp_expected_points'
    }

In [9]:
# Mark bye weeks before filling NaNs in other columns.

full_bear[full_bear['Opp']=='Bye Week'].fillna(value='BYE', inplace=True, axis=0)

C:\Users\fitzp\Anaconda3\lib\site-packages\pandas\core\frame.py:4153: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,

In [10]:
full_bear.rename(column_clean_dict, inplace=True, axis=1)

full_bear.drop('Unnamed: 4', axis=1, inplace=True)

full_bear['OT'].fillna(value=0, inplace=True)
full_bear['OT'].replace({'OT': 1}, inplace=True)

full_bear['Home/Away'].fillna(value='HOME', inplace=True)
full_bear['Home/Away'].replace({'@': 'AWAY'}, inplace=True)

full_bear['team_turnover'].fillna(value=0, inplace=True)
full_bear['oppo_turnover'].fillna(value=0, inplace=True)
full_bear.head(10)

,Week,Day,Date,Kickoff_time,W/L,OT,Rec,Home/Away,Opp,Team_Score,...,team_turnover,1D_allowed,oppo_total_yards,oppo_pass_yards,oppo_rush_yards,oppo_turnover,offense_expected_points,defense_expected_points,sp_expected_points,year
0,1,Sun,September 3,1:00PM ET,L,0,0-1,AWAY,Minnesota Vikings,27.0,...,1.0,17.0,374.0,188.0,186.0,1.0,13.33,-11.18,-4.30,2000
1,2,Sun,September 10,1:01PM ET,L,0,0-2,AWAY,Tampa Bay Buccaneers,0.0,...,4.0,21.0,327.0,171.0,156.0,0.0,-35.01,-8.90,1.97,2000
2,3,Sun,September 17,3:16PM ET,L,0,0-3,HOME,New York Giants,7.0,...,1.0,23.0,409.0,237.0,172.0,1.0,-12.65,-7.19,8.02,2000
3,4,Sun,September 24,1:02PM ET,L,0,0-4,HOME,Detroit Lions,14.0,...,5.0,15.0,274.0,194.0,80.0,1.0,-15.69,8.30,-0.80,2000
4,5,Sun,October 1,4:15PM ET,W,0,1-4,AWAY,Green Bay Packers,27.0,...,0.0,22.0,364.0,320.0,44.0,3.0,1.20,6.05,-4.07,2000
5,6,Sun,October 8,1:03PM ET,L,0,1-5,HOME,New Orleans Saints,10.0,...,3.0,24.0,403.0,217.0,186.0,1.0,-15.93,-7.04,2.11,2000
6,7,Sun,October 15,8:35PM ET,L,0,1-6,HOME,Minnesota Vikings,16.0,...,0.0,17.0,368.0,177.0,191.0,1.0,-1.58,-10.76,-1.71,2000
7,8,Sun,October 22,1:03PM ET,L,0,1-7,AWAY,Philadelphia Eagles,9.0,...,1.0,17.0,298.0,201.0,97.0,2.0,-11.20,8.86,-1.15,2000
8,9,NaN,NaN,NaN,NaN,0,NaN,HOME,Bye Week,NaN,...,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,2000
9,10,Sun,November 5,1:02PM ET,W,0,2-7,HOME,Indianapolis Colts,27.0,...,0.0,20.0,371.0,281.0,90.0,2.0,7.91,-0.90,-1.93,2000

In [11]:
full_bear.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 353 entries, 0 to 16
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Week                     348 non-null    object
 1   Day                      328 non-null    object
 2   Date                     333 non-null    object
 3   Kickoff_time             328 non-null    object
 4   W/L                      328 non-null    object
 5   OT                       353 non-null    int64
 6   Rec                      328 non-null    object
 7   Home/Away                353 non-null    object
 8   Opp                      348 non-null    object
 9   Team_Score               328 non-null    float64
 10  Oppo_score               328 non-null    float64
 11  1D_gained                328 non-null    float64
 12  Team_Total_Yards         328 non-null    float64
 13  Team_Pass_Yards          328 non-null    float64
 14  Team_Rush_Yards          328 non-null    float64
 15  team_turnover            353 non-null    float64
 16  1D_allowed               328 non-null    float64
 17  oppo_total_yards         328 non-null    float64
 18  oppo_pass_yards          328 non-null    float64
 19  oppo_rush_yards          328 non-null    float64
 20  oppo_turnover            353 non-null    float64
 21  offense_expected_points  328 non-null    float64
 22  defense_expected_points  328 non-null    float64
 23  sp_expected_points       328 non-null    float64
 24  year                     353 non-null    int64
dtypes: float64(15), int64(2), object(8)
memory usage: 71.7+ KB